name: Validate Code

on:
  # Run on pull requests
  pull_request:
    branches:
      - main
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Allow being called from other workflows
  workflow_call:

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install additional dependencies
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          rustup default stable
          rustup show
          cargo --version

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Setup Node.js with PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Run validation
        run: pnpm run validate
